export const GET_LIST_OF_CITIES = "GET_LIST_OF_CITIES";
export const ADD_CITY_TO_FAVE = "ADD_CITY_TO_FAVE";
export const REMOVE_CITY_FROM_FAVE = "REMOVE_CITY_FROM_FAVE";
export const GET_FAVE_CITIES = "ADD_CITY_TO_FAVE";




